services:
  api:
    build:
      context: .
      target: final
    command: ./metered_api_server
    ports: 
     - 8080:443

  postgres:
    volumes: 
      - data:/var/lib/postgresql/data

volumes:
  data:






