version: '3.5'

services:
  api: 
    environment:
      - PG_USER=postgres
      - HOST=postgres
      - PG_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    depends_on:
      - postgres

  postgres: 
    image: postgres:11.20-alpine3.18
    restart: no
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password

secrets:
  db_password: 
    file: pg_password.txt
