services:
  api:
    build:
      context: .
      target: final
    image: kakshipth/metered-api-server:prod0.3
    command: ./metered_api_server
    ports: 
     - 443:8080

  postgres:
    volumes: 
      - data:/var/lib/postgresql/data

volumes:
  data:






